num1=int(input(print("enter the num1:")))
num2=int(input(print("enter the num2:")))
add=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
rem=num1%num2
pow=num1**num2
print("addition= ",add)
print("substraction= ",sub)
print("multiplication= ",mul)
print("division= ",div)
print("reminder= ",rem)
print("power =",pow)
